services:
  app:
    image: sampleapp:1.0
   # command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
   # working_dir: /app
    volumes:
      - todo-db:/etc/todos
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
  todo-db: